### ISSUE TITLE
Are `Results` meant to be included into next version(s) asp.net?

### ISSUE THREAD

**Issue by codefactorydevelopment** [DamianEdwards/MinimalApis.Extensions#10]
With respect to unit testing problem (Nick Chapsas video) and solution presented in this repository `Results` folder...will this solution be included in future releases of asp.net? Or is it meant to be used as an extension?

I guess it boils down to question: is it safe to use it for longer runs?

**Comment by DamianEdwards** [comment]
There's no explicit plans yet as far as I know as to whether the various `Result` types will be included in .NET 7. The point of this project is to use it though, so if you find any issue that prevents you using it in your project please do let me know.
