### ISSUE TITLE
Bug on UpdateTodo method

### ISSUE THREAD

**Issue by wbail** [DamianEdwards/MinimalApis.Extensions#21]
In the sample project **TodosApi.Dapper**, the method ```UpdateTodo``` has a bug:

The method receives an ```id``` as well as the entity to be updated. Although, the update statement uses the entity id and not the id passed via parameter.

If the user sends a random id, there's no difference because the method uses the entity id and will update it.

Possible fix:

- Validate if the id is the same as the entity id, if not, returns an error message.

**Comment by DamianEdwards** [comment]
Thanks, to keep it simple it should just be using the id parameter.
