### ISSUE TITLE
WithParameterValidation() requires annotations in the form of [property: AttributeName]

### ISSUE THREAD

**Issue by julioct** [DamianEdwards/MinimalApis.Extensions#37]
I tried WithParameterValidation() from the latest prerelease of MinimalApis.Extensions like this:

```csharp
app.MapPost("/items", async (CreateItemDto itemDto, IItemsRepository repository) =>
{
  // Body here...
})
.WithParameterValidation();

public record CreateItemDto([Required] string Name, string Description, [Range(1, 1000)] decimal Price);
```

Neither the [Required] nor the [Range] validations got enforced at all at runtime. Then I changed to this [property: AttributeName] syntax to specify the data annotations (as I found in one of the examples):

```csharp
public record CreateItemDto([property: Required] string Name, string Description, [property: Range(1, 1000)] decimal Price);
```

And now validations are working properly. 

What's the difference? Did I miss something?

**Comment by DamianEdwards** [comment]
That's a limitation of MiniValidation right now: https://github.com/DamianEdwards/MiniValidation/issues/31
